### ISSUE TITLE
如何显示全部图片？

### ISSUE THREAD

**Issue by ppnman** [vscode-extension/vscode-background-cover#11]
目前只能显示一张图片的一部分，如下所示
![image](https://user-images.githubusercontent.com/39628662/58313202-95a26c80-7e3f-11e9-812b-9ab66792222e.png)
这是原图
![image](https://user-images.githubusercontent.com/39628662/58313225-a05d0180-7e3f-11e9-8dce-bab64bfecb30.png)
可以看到插件只显示了图片的一部分。
还有一个问题就是加载的时候，图片会有部分被挡住。
![image](https://user-images.githubusercontent.com/39628662/58313257-b965b280-7e3f-11e9-8bbb-8df21e191970.png)

**Comment by AShujiao** [comment]
抱歉，不行。参考：background-size的cover特定值会保持图像本身的宽高比例，将图片缩放到正好完全覆盖定义背景的区域。

**Comment by ppnman** [comment]
![image](https://user-images.githubusercontent.com/39628662/58370982-9c180d80-7f3f-11e9-9704-5ae08570a49c.png)
可是我无法找到background-size的定义。

**Comment by ppnman** [comment]
放弃了，换个插件。
