### ISSUE TITLE
1.35不生效了

### ISSUE THREAD

**Issue by lizhuangs** [vscode-extension/vscode-background-cover#13]
刚更新了1.35不生效了。win10和deepin linux都没有生效。。

**Comment by AShujiao** [comment]
昨天刚发布了2.0版本，现在使用方式变了，通过左下角的切换背景图来使用，你试下

**Comment by lizhuangs** [comment]
试了下，可以了，但是有个问题，随机目录设置了有什么用，为什么我设置了以后背景图还是同一张。不是每次打开都是随机的么？

**Comment by AShujiao** [comment]
这个疏忽了，之前的版本中是用来使用随机背景功能用的，现在是当你选择目录后，当前目录下的图片会全部展示在选择图片这个选项下。（现在这个版本你不用关心插件的配置项了，只需要通过插件的功能去使用就行了）

**Comment by lizhuangs** [comment]
就是说选择目录后，只能选一张图片？

**Comment by AShujiao** [comment]
> 就是说选择目录后，只能选一张图片？

是的

**Comment by lizhuangs** [comment]
那这个算bug不，还是说以后就是这样了啊~

**Comment by AShujiao** [comment]
。。不是bug，上个版本你添加了目录路径后，只是用来使用命令重启vscode随机更换一个背景图，
现在只是把命令去掉了，需要到这里来使用
![image](https://user-images.githubusercontent.com/14969576/59167335-4b212f80-8b63-11e9-9f9f-04a1b04e27c7.png)
，没有选择目录时这个选项里只有第一条，选择目录后会把图片都展示出来也可以随机选择

**Comment by lizhuangs** [comment]
怎么样做到，每次打开vscode背景图从指定的这个目录随机选择一张照片的？
或者说每次修改的话需要重启vscode，那就本次进入了以后，先随机选一张修改好，下次进来就是另一张了。

**Comment by AShujiao** [comment]
目前没法做到这种，现在只能手动去选择。不过这种想法也不错，下个版本我再加上去。

**Comment by AShujiao** [comment]
2.1.0已发布，加上了你说的这个功能。

**Comment by lizhuangs** [comment]
试了下，不错~谢谢~
