### ISSUE TITLE
无法启用插件

### ISSUE THREAD

**Issue by Angelinanay** [vscode-extension/vscode-background-cover#15]
![企业微信截图_15622317728422](https://user-images.githubusercontent.com/24545670/60654927-786dae80-9e7f-11e9-8eee-cde96daa1381.png)
没有是否启用功能

![image](https://user-images.githubusercontent.com/24545670/60654968-8de2d880-9e7f-11e9-9664-59b7968b176e.png)
在setting.json自己强行加上后，显示配置未知

**Comment by AShujiao** [comment]
2.0版本后已经不存在这个配置选项了，安装插件后通过底部状态栏右下角切换背景图按钮进行使用，可以看下扩展介绍。。

**Comment by Angelinanay** [comment]
已经解决 谢谢
