### ISSUE TITLE
能延迟加载图片吗

### ISSUE THREAD

**Issue by yjhmelody** [vscode-extension/vscode-background-cover#18]
每次打开vsc 都是图片被渲染出来，然后vsc加载完毕后才变成背景。我看了下代码，好像是把图片弄成css样式的，能不能做到延迟几秒渲染图片呢？比如css延迟几秒动态加载

**Comment by AShujiao** [comment]
那就需要用js来实现了吧。如果用js的话就能实现很多功能了，只是目前来讲现在这种修改css文件的方式比较稳妥，如果你有兴趣可以加入来做一下就更好了
