### ISSUE TITLE
Could not work well with vibrancy.

### ISSUE THREAD

**Issue by slanterns** [vscode-extension/vscode-background-cover#19]
Hi, I thried to use it with [vibrancy](https://github.com/EYHN/vscode-vibrancy), an extension to add transparent aero effect to vsc. However, this extension cannot work after I installed vibrancy.
Since the function of these two extensions are complemented, I think it would be better to let them work together.
Thanks!

**Comment by AShujiao** [comment]
看了下，vibrancy也是修改了body的背景样式，好像没有太好的办法解决。。
