### ISSUE TITLE
侧边栏没有图片

### ISSUE THREAD

**Issue by 296230428** [vscode-extension/vscode-background-cover#21]
侧边栏没有图片图片没有

**Comment by AShujiao** [comment]
不会吧！要不就是整个界面没有，不可能存在只有侧边栏没有的情况。能发下截图吗？

**Comment by 296230428** [comment]
![image](https://user-images.githubusercontent.com/19701441/63633274-5b33b000-c678-11e9-9e4f-6adcdd759a72.png)

**Comment by 296230428** [comment]
不知道是不是图片问题 图片大小是1920*1200 关闭侧边栏的话就全部显示了

**Comment by AShujiao** [comment]
我怎么感觉你这个像是用的background插件而不是background-cover

**Comment by 296230428** [comment]
没有 只用一个了 
![image](https://user-images.githubusercontent.com/19701441/63660586-9d303380-c7e9-11e9-8db1-6097532a9a52.png)

**Comment by AShujiao** [comment]
C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css

**Comment by 296230428** [comment]
额 我用的是mac

**Comment by 296230428** [comment]
那这样 我重新装一遍vscode  vscode 里面的配置文件我已经删除了  但不清楚 workbench.main.css 是否删除了  下面是workbench.main.css 的内容 
![image](https://user-images.githubusercontent.com/19701441/63662935-0ff1dc80-c7f3-11e9-80bf-6eaa2fec64fa.png)

**Comment by 296230428** [comment]
下面是我配置文件
![image](https://user-images.githubusercontent.com/19701441/63662991-3ca5f400-c7f3-11e9-83c1-f9654a6419b9.png)

**Comment by AShujiao** [comment]
> 那这样我重新装一遍vscode vscode里面的配置文件我已经删除了但不清楚workbench.main.css是否删除了下面是workbench.main.css的内容
> ![图片](https://user-images.githubusercontent.com/19701441/63662935-0ff1dc80-c7f3-11e9-80bf-6eaa2fec64fa.png)

恩，就是之前的background插件的css没有删除导致的，你直接把插件生成的css都删除了吧，然后重新设置背景试下

**Comment by AShujiao** [comment]
![image](https://user-images.githubusercontent.com/14969576/63663161-e4bbbd00-c7f3-11e9-8572-8a4767fbc1b8.png)
这种才是正常的

**Comment by 296230428** [comment]
我的就是这样css 文件是对的 我刚才试了下别的图片  发现 是这样的  我有两张图片 一张尺寸是1920 * 1200的 就是这张图片侧边栏没有显示, 然后我更换了1920*1080的图片 侧边栏就有了

**Comment by AShujiao** [comment]
这就怪了，样式里添加了background-size:cover;不管图片尺寸大小应该都会全覆盖的

**Comment by 296230428** [comment]
![002](https://user-images.githubusercontent.com/19701441/63663612-ab844c80-c7f5-11e9-8559-e40c1d541100.jpg)你试试这张图片呢

**Comment by AShujiao** [comment]
![image](https://user-images.githubusercontent.com/14969576/63663722-19c90f00-c7f6-11e9-9499-df4c0a83d752.png)
不是插件问题。。你这种纯色黑白背景图片即使全覆盖了你也看不出来效果

**Comment by 296230428** [comment]
.... 好尴尬
