### ISSUE TITLE
mac下好像无法使用？

### ISSUE THREAD

**Issue by y805939188** [vscode-extension/vscode-background-cover#22]
在mac下貌似无法使用。通过右下角图标添加了图片之后没有任何效果。通过vscode控制台发现body上好像并没有添加上背景图片相关属性

**Comment by AShujiao** [comment]
是以管理员身份运行的吗？扩展是通过修改css文件实现的，如果没有相应的权限是修改不成功的

**Comment by y805939188** [comment]
你好，是的，已经是管理员身份了。mac下root用户就是权限最屌的那个

<img width="593" alt="屏幕快照 2019-08-29 下午2 12 15" src="https://user-images.githubusercontent.com/28889103/63914873-15eff380-ca67-11e9-836e-59ac9fa0f0c0.png">

**Comment by AShujiao** [comment]
#21  你参考下这个问题，他用的也是mac，看下你本地的css文件是否正常。如果你vscode和扩展都是最新版本应该没有问题，可能是其它的问题导致的

**Comment by y805939188** [comment]
好的，我参考一下，谢谢
