### ISSUE TITLE
vscode 无法加载css

### ISSUE THREAD

**Issue by manageryzy** [vscode-extension/vscode-background-cover#23]
![image](https://user-images.githubusercontent.com/6567674/64227893-ba66af80-cf17-11e9-9e5e-09cc0765f65f.png)

最近更新后无法使用。和https://github.com/shalldie/vscode-background/issues/165 相同

**Comment by AShujiao** [comment]
C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css
麻烦截图下这个css文件里的内容，然后把插件生成的css给删除掉，再重新打开试下
