### ISSUE TITLE
开启远程开发后扩展失效及临时解决

### ISSUE THREAD

**Issue by staugur** [vscode-extension/vscode-background-cover#24]
vscode发布了预览版的 Remote Development 扩展，我在试用remote wsl中，发现这个扩展安装到wsl后，图片选择无论是本地还是wsl里的，均无效。

后把这个扩展设置为在ui安装并选择本地图片方可：
```
    "remote.extensionKind":{
        "manasxx.background-cover": "ui"
    }
```

不过，还是希望评估看看是否需要适配下。

**Comment by AShujiao** [comment]
2.2.3版本已经将扩展定义为ui了。
