### ISSUE TITLE
mac 启用后无效

### ISSUE THREAD

**Issue by lsxu** [vscode-extension/vscode-background-cover#25]

**Comment by AShujiao** [comment]
请确保是以管理员身份运行的vscode

**Comment by AShujiao** [comment]
> 请确认是mac不是windows mac不知道还怎么再给管理员权限了

mac下好像是以root权限运行，我也没有用过mac不太清楚，你可以搜一下相关信息

**Comment by ycxalyn** [comment]
你好我在mac上能正常运行，但是没你说的那个按钮呢，要如何调整样式呢

**Comment by AShujiao** [comment]
> 你好我在mac上能正常运行，但是没你说的那个按钮呢，要如何调整样式呢

没按钮就是没有正常运行。主要靠底部的按钮来设置的

**Comment by ycxalyn** [comment]
但是我能正常的设置图片呢

**Comment by AShujiao** [comment]
> 但是我能正常的设置图片呢
截图我看下，还有插件的截图
