### ISSUE TITLE
卸载之后背景图片还是存在

### ISSUE THREAD

**Issue by NightLostK** [vscode-extension/vscode-background-cover#30]
卸载之后背景图片还是存在，已经关闭重启 vscode 好几次了仍然存在。

**Comment by AShujiao** [comment]
C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css

**Comment by NightLostK** [comment]
> 卸载后会自动清理css的，除非vscode没有管理员权限无法操作文件，一般是不存在这种情况的。
> 你可以手动清理方法：
> C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css
> 手动打开此文件将扩展添加的body样式删除掉，

应该是因为没有权限的原因，手动在.css文件删除就好了，谢谢~
