### ISSUE TITLE
每次重新加载时都会说VS Code已损坏。

### ISSUE THREAD

**Issue by li2412360774** [vscode-extension/vscode-background-cover#31]
每次修改透明度，重新加载窗口后都会提示，如图。
以及，透明度1也太暗了，能不能直接就是原图显示呢？

**Comment by li2412360774** [comment]
![C@VND61BFLZ%D1S~MQZF%1S](https://user-images.githubusercontent.com/38518506/75131614-da30a080-570e-11ea-96e3-a8f466e39224.png)

**Comment by AShujiao** [comment]
这个提示你可以通过在弹窗右上角点击设置图标选择不再显示 ，不过只能保持到你下次升级vscode之前。原图显示会影响使用vscode所有这个不能做到
