### ISSUE TITLE
我的 settings.json 文件被清空了。。

### ISSUE THREAD

**Issue by Dlouxgit** [vscode-extension/vscode-background-cover#35]
不知道是不是我频繁关开 VSCODE，它背景图片换不过来出了 bug 直接清空了。 wtnl

**Comment by AShujiao** [comment]
有这个可能，更新背景时也会更新配置，但这种情况我还是第一次见。。好像也没太好的解决办法。
![image](https://user-images.githubusercontent.com/14969576/83483894-39ecd380-a4d6-11ea-88e4-d21adf298e89.png)
