### ISSUE TITLE
卸载后的清理有问题？

### ISSUE THREAD

**Issue by voiddreamz** [vscode-extension/vscode-background-cover#36]
选择卸载后，多次重启打开，但是图片仍然存在
![Snipaste_2020-07-12_08-05-38.png](https://i.loli.net/2020/07/12/r9vgF1jXRzbA6Vx.png)

**Comment by voiddreamz** [comment]
(https://i.loli.net/2020/07/12/r9vgF1jXRzbA6Vx.png)

**Comment by AShujiao** [comment]
#30 
尝试下这个

**Comment by AShujiao** [comment]
刚刚确认了下，卸载这块的确有问题，执行卸载钩子失败了。应该是api更新了或者vscode的bug，已经反馈给vscode。。 #102260

**Comment by AShujiao** [comment]
将vscode升级到今天推送的1.47.3版本以及安装本扩展2.2.4版本，然后再卸载即可。。
