### ISSUE TITLE
当图片文件是符号链接时，该插件无法设置背景

### ISSUE THREAD

**Issue by lisonge** [vscode-extension/vscode-background-cover#37]
![image](https://user-images.githubusercontent.com/38517192/90795375-9080e580-e340-11ea-9948-7fe4c794c577.png)

![image](https://user-images.githubusercontent.com/38517192/90795275-69c2af00-e340-11ea-8d2f-862951eb697e.png)

**Comment by AShujiao** [comment]
我试了下没问题的，看我的这个图片缩略图会不会是太暗了看不出来效果。。换个图片用相同的文件名试下。。

**Comment by AShujiao** [comment]
刚才理解错了，我还以为是你文件名带个特殊符号呢。。。符号链接这种文件我还是头一次听说，可能不支持css使用吧。。

**Comment by lisonge** [comment]
硬链接是没问题的，符号链接8行
