### ISSUE TITLE
请问你演示的这些背景卡通图片有链接吗？

### ISSUE THREAD

**Issue by gwd0715** [vscode-extension/vscode-background-cover#38]
如题

**Comment by AShujiao** [comment]
等有时间我上传到百度云分享给你吧，现在电脑上没有这些图片。（另外这个是守望先锋游戏里的英雄人物。。。）

**Comment by gwd0715** [comment]
好嘞 谢谢

**Comment by AShujiao** [comment]
链接：https://pan.baidu.com/s/15pM381Cqsmz4jWe3cqPZGw 
提取码：qqzf

你要的图片来了。。
