### ISSUE TITLE
请问mac版本的怎么设置？我设置选择了图片，但是无效

### ISSUE THREAD

**Issue by momolea** [vscode-extension/vscode-background-cover#41]
我的wins10系统的vscode载入背景图是没问题的，完美展示。但是我用我得mac安装了组件，也是按着步骤来start,并且也选择了一张图片，但是重启vscode，显示无效......不知该如何解决此问题，期望您的解答

**Comment by AShujiao** [comment]
应该是没有权限，请用root权限运行。类似windows超级管理员运行方式。

**Comment by momolea** [comment]
谢谢🙏 已经好了
| |
leaolly
|
|
leaolly333@163.com
|
签名由网易邮箱大师定制


在2020年09月17日 08:49，ashujiao<notifications@github.com> 写道：

应该是没有权限，请用root权限运行。类似windows超级管理员运行方式。

**Comment by momolea** [comment]
> 应该是没有权限，请用root权限运行。类似windows超级管理员运行方式。
谢谢已经好了
