### ISSUE TITLE
Choose Picture By DropDown

### ISSUE THREAD

**Issue by Hector7500** [vscode-extension/vscode-background-cover#8]
Sorry if I shouldn't be posting this here, not sure if you take Feature Request on this side 

But if you do this is the request 

The way it reads the folder path once its provide you can choose any picture in there with a drop down or in the settings without having to find the path or remember the name and so you can easily just change the images on the click of a button. 

If I am allowed to feature request here even if this one isn't approved or a good time for release and gets closed please let me know if it's ok to do feature request here (so in the future I can provide more suggestion/request).

Thank you in Advance!

**Comment by AShujiao** [comment]
Update the extension, there should be what you want

![](https://user-images.githubusercontent.com/14969576/55158915-f7758b80-519a-11e9-9699-9db0ed771c91.gif)

**Comment by Hector7500** [comment]
Thank you!!!!! IT Works!!!!
