### ISSUE TITLE
imagePath设置引用https图片失败

### ISSUE THREAD

**Issue by staugur** [vscode-extension/vscode-background-cover#9]
你好，请教一个配置问题，依照[https://github.com/vscode-extension/vscode-background-cover#notice-提示](https://github.com/vscode-extension/vscode-background-cover#notice-%E6%8F%90%E7%A4%BA)，图片应该是支持https引用吧。

我这里同一张图片，放到本地可以显示；引用远程提示“背景更新失败，请确认路径是否正确”，配置是： `"backgroundCover.imagePath": "https://img.saintic.com/ImgBg/VSCodeBgImg/1.jpg"`

版本: 1.33.0 (system setup)
提交: 0dd516dd412d42323fc3464531b1c715d51c4c1a
日期: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by AShujiao** [comment]
> 你好，请教一个配置问题，依照[https://github.com/vscode-extension/vscode-background-cover#notice-提示](https://github.com/vscode-extension/vscode-background-cover#notice-%E6%8F%90%E7%A4%BA)，图片应该是支持HTTPS引用吧。
> 
> 我这里同一张图片，放到本地可以显示;引用远程提示“背景更新失败，请确认路径是否正确”，配置是： `"backgroundCover.imagePath": "https://img.saintic.com/ImgBg/VSCodeBgImg/1.jpg"`
> 
> 版本：1.33.0（系统设置）
> 提交：0dd516dd412d42323fc3464531b1c715d51c4c1a 
> 日期：2019-04-04T15：14：28.026Z 
> 电子：3.1.6 
> Chrome：66.0.3359.181 
> Node.js：10.2.0 
> V8：6.6.346.32 
> 操作系统：Windows_NT x64 10.0.17134

抱歉，上次更新版本加了一些验证的功能，导致出现了一些bug，晚上我修复下

**Comment by staugur** [comment]
顺道说一个，目前版本在加载窗口时，发现背景图片平铺了，不知道加个`background-repeat: no-repeat;`会不会体验更好？

**Comment by AShujiao** [comment]
> 顺道说一个，目前版本在加载窗口时，发现背景图片平铺了，知道不加个`background-repeat: no-repeat;`会不会体验更好？

嗯嗯可以，目前正在打算弄2.0新版到时候加上去。现在应该可以https的链接了

**Comment by staugur** [comment]
:+1: https引用正常！期待新版本！
